insert into centro_aula("id", "nome") values (1,'Centro de Aulas Aroeira')
insert into centro_aula("id", "nome") values (2,'Centro de Aulas Baru')
insert into centro_aula("id", "nome") values (3,'Centro de Aulas Caraíbas')
insert into centro_aula("id", "nome") values (4,'Centro de Aulas D')
insert into centro_aula("id", "nome") values (5,'Faculdade de Educação Física')
insert into centro_aula("id", "nome") values (6,'INF-Instituto de Informática')
insert into centro_aula("id", "nome") values (7,'Instituto de Estudos Sócio-ambientais')